# Generated by Django 5.0.3 on 2024-03-10 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_auth_type_user_auth_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_country',
            field=models.CharField(choices=[('Uzbekistan', 'Uzbekistan'), ('Koreya', 'Koreya'), ('Kazakstan', 'Kazakstan'), ('America', 'America'), ('Russia', 'Russia')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usercodeverification',
            name='auth_country',
            field=models.CharField(choices=[('Uzbekistan', 'Uzbekistan'), ('Koreya', 'Koreya'), ('Kazakstan', 'Kazakstan'), ('America', 'America'), ('Russia', 'Russia')], max_length=20),
        ),
    ]
